"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListManager = void 0;
var DragAndDropWrapper_1 = require("./DragAndDropWrapper/DragAndDropWrapper");
var withMaxItems_1 = require("./withMaxItems/withMaxItems");
var withReactToItemsChange_1 = require("./withReactToItemsChange/withReactToItemsChange");
var uuid_1 = require("uuid");
var ComponentWithMaxItems = (0, withMaxItems_1.withMaxItems)(DragAndDropWrapper_1.DragAndDropWrapper, uuid_1.v4);
var ComponentWithReactToItemsChange = (0, withReactToItemsChange_1.withReactToItemsChange)(ComponentWithMaxItems);
exports.ListManager = ComponentWithReactToItemsChange;
